// try { 
//   console.log(naoExisto);
// } catch(err) {
//     console.log('NaoExisto não existe.')
// }


try {
  // é executa quando não há erros
} catch (e) {
  // é executada quanda há erros
  console.log('Tratando o erro');
} finally {
  // sempre 
}